#
# Used for docker and development
#
# globals
backend-servers = ["rabbit:1883"]
user = "guest"
pass = "guest"

# read timeout in seconds
read-timeout = 30

[mqtt-store]
connection-string = "root@tcp(mysql:3306)/ninja"
mqtt-select = "select at.userID, at.mqtt_client_id from accesstoken at, accesstoken_scope ats where at.id = ats.accesstoken and ats.scope_domain in ('mqtt', '*') and ats.scope_item = '*' and at.id = ?"

[mqtt]
listen-address = ":6300"